baseURL = "https://wretiii.com/"
languageCode = "en-us"
title = "Chris Green"
theme = "qubt-hugo"

[params]
#  name = "Chris Green"
  description = "Security Consultant | Penetration Tester | Speaker <br> CISSP, OSCP, CISSP, CISA, CRISC, QSA/PCIP, CMMC RP"
  favicon = "/images/mu-favicon.svg"
  logo_light = "/images/mu-light.svg"
  logo_dark = "/images/mu-dark.svg"

[params.author]
  image = "/images/computers-dark.png"

# Main menu links
[menu]

  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "talks"
    name = "Talks"
    url = "/talks/"
    weight = 2

  # [[menu.main]]
  #   identifier = "blog"
  #   name = "Blog"
  #   url = "/posts/"
  #   weight = 3

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 4

[markup]
  defaultMarkdownHandler = "goldmark"

  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

