baseURL = "https://wretiii.com/"
languageCode = "en-us"
title = "Chris Green"
theme = "qubt-hugo"

[params]
#  name = "Chris Green"
  description = "Security Consultant | Penetration Tester | Speaker <br> CISSP, OSCP, CISSP, CISA, CRISC, QSA/PCIP, CMMC RP"
  favicon = "/images/mu-favicon.svg"
  logo_light = "/images/mu-light.svg"
  logo_dark = "/images/mu-dark.svg"

[params.author]
  image = "/images/computers-dark.png"

# Social profiles
[[params.social]]
  name = "linkedin"
  icon = "fa-brands fa-linkedin"
  url = "https://www.linkedin.com/in/christophermgreen/"

[[params.social]]
  name = "bluesky"
  icon = "fa-brands fa-bluesky"
  url = "https://bsky.app/profile/wreti.bsky.social"

[[params.social]]
  name = "twitter"
  icon = "fa-brands fa-twitter"
  url = "https://x.com/wreti"

[[params.social]]
  name = "mastodon"
  icon = "fa-brands fa-mastodon"
  url = "https://mastodon.social/@wreti"
  
[[params.social]]
  name = "github"
  icon = "fa-brands fa-github"
  url = "https://github.com/wretiii"

# Main menu links
[menu]

  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "talks"
    name = "Talks"
    url = "/talks/"
    weight = 2

  # [[menu.main]]
  #   identifier = "blog"
  #   name = "Blog"
  #   url = "/posts/"
  #   weight = 3

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 4

[markup]
  defaultMarkdownHandler = "goldmark"

  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

