baseURL = "https://wretiii.com/"
languageCode = "en-us"
title = "Chris Green"
theme = "qubt-hugo"

[params]
  name = "Chris Green"
  description = "Security Consultant | Speaker | Writer"
  favicon = "/images/mu-favicon.svg"  # place your favicon in static/images/

[params.author]
  image = "/images/mu-dark.svg"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "talks"
    name = "Talks"
    url = "/talks/"
    weight = 2

#  [[menu.main]]
#    identifier = "blog"
#    name = "Blog"
#    url = "/posts/"
#    weight = 3

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 4

[markup]
  defaultMarkdownHandler = "goldmark"

  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

